# Generated by Django 5.0.3 on 2024-03-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('unique_code', models.IntegerField()),
                ('status', models.CharField(choices=[('Before', 'Before the meeting'), ('During', 'During the meeting'), ('After', 'After the meeting'), ('Archival', 'Meeting was archived'), ('Removed', 'Meeting was removed')], default='Before', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingChatMessage',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=255)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='Images/% Y/% m/% d/')),
                ('url_link', models.URLField()),
                ('likes', models.CharField(choices=[('Nothing', 'No comments added'), ('Like', 'Good message'), ('Dislike', 'Bad message')], default='Nothing', max_length=30)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommonMeeting.meeting')),
            ],
        ),
    ]
