# Generated by Django 5.0.3 on 2024-03-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonMeeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingchatmessage',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meetingchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='meetingchatmessage',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meetingchatmessage',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
