# Generated by Django 5.0.3 on 2024-03-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonMeeting', '0002_meetingchatmessage_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingchatmessage',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meetingchatmessage',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
