# Generated by Django 5.0.3 on 2024-03-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonMeeting', '0003_alter_meeting_id_alter_meetingchatmessage_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingchatmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
