# Generated by Django 5.0.3 on 2024-03-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonMeeting', '0004_alter_meetingchatmessage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='unique_code',
            field=models.CharField(max_length=20),
        ),
    ]
